Update RobotoFlex.designspace
—comment instances because builder fails to generate static instances, it doesn’t support quadratic curves:

fontmake.errors.FontmakeError: In RobotoFlex.designspace -> instances/RobotoFlex_Thin.ufo: Compiling UFO failed: ( Trying to perform operation on unsupported segment type., qcurve )